import { Booking, BookingDraft, PaymentSummary, ReviewSubmitRequest, ServiceItem, Store, StoreReview, Therapist, TimePeriodCode, TimeSlot, TimeSlotStatus } from '../types/domain';
export interface HomeQuickAction { key: string; title: string; subtitle: string; }
export interface ServiceCardMetaCopy { durationUnit: string; servedPrefix: string; servedSuffix: string; }
export interface StoreCardMetaCopy { ratingUnit: string; nextAvailablePrefix: string; }
export interface OrderCardMetaCopy { paidPrefix: string; }
export interface HomeCopy { locationText: string; heroTitle: string; searchPlaceholder: string; quickActions: HomeQuickAction[]; frequentTitle: string; frequentMoreText: string; nearbyTitle: string; nearbySortText: string; featuredServiceTitle: string; featuredServiceMoreText: string; memberTitle: string; memberSummary: string; memberActionText: string; storeCardMeta: StoreCardMetaCopy; serviceCardMeta: ServiceCardMetaCopy; }
export interface HomePayload { frequentStores: Store[]; nearbyStores: Store[]; featuredServices: ServiceItem[]; featuredTherapists: Therapist[]; copy: HomeCopy; }
export interface PageResult<T> { items: T[]; page: number; pageSize: number; total: number; hasMore: boolean; }
export interface PaymentLine { key: string; label: string; amountText: string; tone?: 'discount' | 'default'; }
export interface WechatPaymentParameters { timeStamp: string; nonceStr: string; package: string; signType: 'RSA' | 'MD5' | 'HMAC-SHA256'; paySign: string; mockPayment?: boolean; }
export interface BookingPaymentPayload { bookingId: string; amount: number; paymentNo: string; parameters: WechatPaymentParameters; }
export interface ConfirmationFormCopy { guestCountLabel: string; contactLabel: string; contactPlaceholder: string; remarkLabel: string; remarkPlaceholder: string; contactRequiredMessage: string; submitFallbackText: string; }
export interface ConfirmationEditActionCopy { store: string; service: string; therapist: string; time: string; }
export interface BookingConfirmationPayload { pageTitle: string; editActions: ConfirmationEditActionCopy; cardMeta: ServiceCardMetaCopy; store: Store; service: ServiceItem; therapist?: Therapist; therapistDisplayName: string; scheduledAt: string; payment: PaymentSummary; formCopy: ConfirmationFormCopy; benefitTitle: string; benefitSelectionText: string; paymentTitle: string; paymentLines: PaymentLine[]; totalLabel: string; agreementText: string; agreementRequiredMessage: string; depositButtonText: string; }
export interface OrderTabItem { key: string; label: string; statuses?: Booking['status'][]; }
export interface OrderDictionaryPayload { pageTitle: string; detailTitle: string; statusLabel: Record<string, string>; actionLabel: Record<string, string>; tabs: OrderTabItem[]; detailSteps: string[]; codeTitle: string; codeHint: string; codeExtraHint: string; detailFields: { service: string; therapist: string; scheduledAt: string; contact: string }; paymentTitle: string; paymentFields: { item: string; therapist: string; discount: string; paid: string }; actionSectionTitle: string; checkinButtonText: string; cancelModalTitle: string; cancelModalContent: string; cancelModalConfirmText: string; cancelSuccessToastText: string; paySuccessToastText: string; payFailureToastText: string; cardMeta: OrderCardMetaCopy; serviceCardMeta: ServiceCardMetaCopy; storeCardMeta: StoreCardMetaCopy; }
export interface ReviewDictionaryPayload { tags: string[]; pageTitle: string; ratingFields: { therapist: string; environment: string; service: string }; contentPlaceholder: string; imageSectionTitle: string; imageHintText: string; addImageText: string; uploadingImageText: string; uploadFailedText: string; retryUploadText: string; anonymousText: string; agreementText: string; submitButtonText: string; submittedButtonText: string; submittingToastText: string; submittedToastText: string; maxTagValidationText: string; maxTagToastText: string; agreementRequiredMessage: string; contentMinLengthMessage: string; }
export interface SortOption<K extends string = string> { key: K; label: string; }
export interface ServiceDictionaryPayload { pageTitle: string; categories: string[]; allCategory: string; storeSwitchLabel: string; searchPlaceholder: string; clearSearchText: string; sortOptions: Array<SortOption<'recommended' | 'sales' | 'price'>>; cardMeta: ServiceCardMetaCopy; storeCardMeta: StoreCardMetaCopy; bannerText: string; detailTitle: string; loadingTitle: string; loadingDescription: string; errorTitle: string; errorMessage: string; retryText: string; loadMoreText: string; favoriteText: string; favoritedText: string; shareText: string; memberPriceLabel: string; introTitle: string; processTitle: string; suitableTitle: string; noticeTitle: string; noticeText: string; recommendedTherapistTitle: string; nextAvailablePrefix: string; reviewTitle: string; reviewSummarySuffix: string; primaryButtonText: string; favoriteAddedToast: string; favoriteRemovedToast: string; }
export interface TimePeriodOption { key: TimePeriodCode; label: string; }
export interface TimeDictionaryPayload { dates: string[]; periods: TimePeriodOption[]; defaultPeriod: TimePeriodCode; statusLabel: Record<TimeSlotStatus, string>; legend: Array<{ status: TimeSlotStatus; label: string }>; }
export interface TherapistMetaCopy { experiencePrefix: string; experienceSuffix: string; ratingUnit: string; serviceCountPrefix: string; serviceCountSuffix: string; }
export interface TherapistDictionaryPayload { pageTitle: string; modes: Array<{ key: 'specified' | 'auto'; label: string }>; autoHint: string; nextAvailablePrefix: string; specifyFeePrefix: string; availableText: string; unavailableText: string; metaCopy: TherapistMetaCopy; }
export interface SuccessCopy { title: string; subtitle: string; bookingCodePrefix: string; codeHint: string; navigationActionText: string; contactActionText: string; reminderText: string; detailButtonText: string; homeButtonText: string; }
export interface BookingSuccessPayload { booking: Booking; copy: SuccessCopy; }
export interface BookingRebookPayload { sourceBookingId: string; draft: BookingDraft; }
export interface BookingReschedulePayload { sourceBookingId: string; draft: BookingDraft; }
export interface ReviewImageUploadPayload { imageUrl: string; }
export interface ProfileUser { name: string; phone: string; avatarText: string; level: string; balanceText: string; couponCount: number; packageCount: number; }
export interface LoginCopyPayload { brandMark: string; brandName: string; brandSubtitle: string; welcomeText: string; panelTitle: string; phoneLabel: string; phonePlaceholder: string; codeLabel: string; codePlaceholder: string; sendCodeText: string; loginButtonText: string; loggingInText: string; agreementText: string; wechatEntryText: string; codeSentToastText: string; agreementRequiredToastText: string; phoneInvalidMessage: string; codeInvalidMessage: string; demoCode: string; }
export interface LoginCodePayload { mobile: string; requestId: string; expiresIn: number; verificationCode?: string; }
export interface LoginPayload { token: string; expiresIn: number; user: { mobile: string; name: string; avatarText: string }; }
export interface ProfilePayload { user: ProfileUser; title: string; settingsIcon: string; memberTitle: string; memberSubtitle: string; memberStats: string[]; shortcuts: HomeQuickAction[]; recentBookingTitle: string; recentBookingActionText: string; menuItems: Array<{ key: string; label: string; valueText: string }>; logoutText: string; logoutModalTitle: string; logoutModalContent: string; logoutConfirmText: string; logoutCancelText: string; }
export interface CheckinDictionaryPayload { title: string; qrTitle: string; refreshText: string; steps: string[]; pendingButtonText: string; checkingButtonText: string; checkedButtonText: string; successToastText: string; failureToastText: string; bottomActions: Array<{ key: string; label: string }>; }
export interface StoreDetailDictionaryPayload { actions: Array<{ key: string; label: string }>; recommendedServiceTitle: string; allServiceText: string; primaryButtonText: string; loadingTitle: string; loadingDescription: string; errorTitle: string; errorMessage: string; retryText: string; loadMoreText: string; favoriteActiveText: string; favoriteAddedToast: string; favoriteRemovedToast: string; panels: { facilities: string; businessHours: string; notice: string }; expandText: string; collapseText: string; businessHoursText: string; noticeText: string; tabs: Array<{ key: 'services' | 'therapists' | 'reviews'; label: string }>; reviewTitle: string; reviewSummarySuffix: string; storeCardMeta: StoreCardMetaCopy; serviceCardMeta: ServiceCardMetaCopy; }
export interface ActionFeedbackDictionaryPayload { supportUnavailable: string; genericMockAction: string; distanceSorted: string; mapUnavailable: string; navigationUnavailable: string; contactPlaceholder: string; shareUnavailable: string; therapistUnavailable: string; slotFull: string; checkinRepeated: string; codeRefreshed: string; codeRefreshHint: string; codeRefreshFailed: string; minGuestCount: string; maxGuestCount: string; cancelUnavailable: string; }
export interface PageStateCopy { loadingTitle: string; loadingDescription: string; errorTitle: string; errorMessage: string; retryText: string; emptyTitle?: string; emptyDescription?: string; }
export interface StoreListStateCopy extends PageStateCopy { pageTitle: string; searchPlaceholder: string; businessOnlyText: string; sortOptions: Array<SortOption<'frequent' | 'distance' | 'rating'>>; cardMeta: StoreCardMetaCopy; mapEntryText: string; locationReadyText: string; locateActionText: string; locationDeniedWarning: string; locationFailedWarning: string; }
export interface ConfirmStateCopy extends PageStateCopy { submitErrorTitle: string; submitErrorMessage: string; paymentRefreshErrorMessage: string; }
export interface TherapistStateCopy extends PageStateCopy { unavailableFilterText: string; availableOnlyFilterText: string; emptySummaryText: string; selectedSummaryTitle: string; autoSummaryTitle: string; nextButtonText: string; }
export interface TimeStateCopy extends PageStateCopy { pageTitle: string; noticeText: string; emptyActionDateText: string; emptyActionTherapistText: string; selectedSummaryTitle: string; nextButtonText: string; emptySlotText: string; }
export interface CheckinStateCopy extends PageStateCopy { submitErrorTitle: string; submitErrorMessage: string; refreshCodeText: string; }
export interface ReviewStateCopy extends PageStateCopy { submitErrorTitle: string; submitErrorMessage: string; }
export interface PageStateDictionaryPayload { home: PageStateCopy; stores: StoreListStateCopy; services: PageStateCopy; orders: PageStateCopy; confirm: ConfirmStateCopy; bookingDetail: PageStateCopy; therapist: TherapistStateCopy; time: TimeStateCopy; checkin: CheckinStateCopy; review: ReviewStateCopy; success: PageStateCopy; profile: PageStateCopy; }
export interface BookingService { getHome():Promise<HomePayload>; getStores():Promise<Store[]>; getServices():Promise<ServiceItem[]>; getStore(id:string):Promise<Store>; getService(id:string):Promise<ServiceItem>; getTherapists(serviceId:string):Promise<Therapist[]>; getTimeSlots(draft?:BookingDraft):Promise<TimeSlot[]>; getBookingConfirmation(draft:BookingDraft):Promise<BookingConfirmationPayload>; getOrderDictionaries():Promise<OrderDictionaryPayload>; getReviewDictionaries():Promise<ReviewDictionaryPayload>; getServiceDictionaries():Promise<ServiceDictionaryPayload>; getStoreDetailDictionaries():Promise<StoreDetailDictionaryPayload>; getTimeDictionaries():Promise<TimeDictionaryPayload>; getTherapistDictionaries():Promise<TherapistDictionaryPayload>; getSuccessCopy():Promise<SuccessCopy>; getLoginCopy():Promise<LoginCopyPayload>; sendLoginCode(mobile:string):Promise<LoginCodePayload>; login(mobile:string, code:string):Promise<LoginPayload>; getBookingSuccess(id:string):Promise<BookingSuccessPayload>; getBookingRebookDraft(id:string):Promise<BookingRebookPayload>; getBookingRescheduleDraft(id:string):Promise<BookingReschedulePayload>; getProfile():Promise<ProfilePayload>; getCheckinDictionaries():Promise<CheckinDictionaryPayload>; getActionFeedbackDictionaries():Promise<ActionFeedbackDictionaryPayload>; getPageStateDictionaries():Promise<PageStateDictionaryPayload>; createBooking(draft:BookingDraft, requestId:string):Promise<Booking>; rescheduleBooking(draft:BookingDraft, requestId:string):Promise<Booking>; getBookings():Promise<Booking[]>; getBooking(id:string):Promise<Booking>; getStoreReviews(storeId:string, serviceId?:string, page?:number, pageSize?:number):Promise<PageResult<StoreReview>>; checkinBooking(id:string, requestId:string):Promise<Booking>; refreshBookingCode(id:string, requestId:string):Promise<Booking>; cancelBooking(id:string, requestId:string):Promise<Booking>; prepareBookingPayment(id:string, requestId:string):Promise<BookingPaymentPayload>; payBooking(id:string, requestId:string):Promise<Booking>; uploadReviewImage(tempFilePath:string, requestId:string):Promise<ReviewImageUploadPayload>; submitReview(request:ReviewSubmitRequest, requestId:string):Promise<Booking>; }
