schema_version: ENC[AES256_GCM,data:TA==,iv:bHcqWT5utoEpacGQzxZq6zyp5Rqjtxsy3LhqM5gof2A=,tag:5M+39mw0b/hufEH624E88w==,type:int]
java_backend:
    application_url: ENC[AES256_GCM,data:h//LuzOyNKBU,iv:lZL1X/90zGNmKaN62iULNwntUIpguQRhpNNTE+ke0EM=,tag:n9yT0IjNq1r/0bBDh8r1Ig==,type:str]
    environment:
        SPRING_PROFILES_ACTIVE: ENC[AES256_GCM,data:2gA=,iv:VO65Z7h17YvTyHZTlYjG2H6wV9qTBmnPJvwyg9179YI=,tag:yfafuTK3MqGGqo6z+fkWpA==,type:str]
        JAVA_OPTS: ENC[AES256_GCM,data:GAkfVGRQX4aBdnbQtsifiuzshHXMi+XiQw==,iv:JhLGWumtPcVysWONG18q3a8REF1Fm2SX6iELI+qANDQ=,tag:Ula2hqgiFxJgNebD4BiVMg==,type:str]
        QIYU_DB_URL: ENC[AES256_GCM,data:0r+Vig4fTq1A,iv:sGRuCzn2aJnc4pmxOEP4vZg4C6wNOQzFMR/LJL/3CTI=,tag:ATcAStCkJ79gH9dCVrcWhA==,type:str]
        QIYU_DB_USERNAME: ENC[AES256_GCM,data:N5T1a2iSDWU9,iv:XFyRPHuW36UpHXQrANFk4ATbbIsRl8peF0C7M9vjgvA=,tag:s1YQXoczL0cs8UsTAtz2Dg==,type:str]
        QIYU_DB_PASSWORD: ENC[AES256_GCM,data:PKnz45XcnZin,iv:Yk531vlPtOMqYelr+ConKwtnnXBr+PPLx0flnk8B/zY=,tag:iTg9u8eUwK/PyhK5wx+BnQ==,type:str]
        SPRING_DATA_REDIS_HOST: ENC[AES256_GCM,data:YdGUOvLZInMkhFom4syuqGHE+yo=,iv:A1cU5t06jyLXztUHth8X46bRvC9oHT17uuwmKkepSJQ=,tag:nJ4nkwyocQNteeOyc4fB/Q==,type:str]
        SPRING_DATA_REDIS_PORT: ENC[AES256_GCM,data:ilpR/g==,iv:7XWBOm/4mg3oncEtAIU4rj+ORhhSIcD6cXxi9tMcG2E=,tag:9Uf6DYIu2VHErveOlTuF+w==,type:str]
        SPRING_DATA_REDIS_PASSWORD: ""
        ADMIN_INITIAL_PASSWORD: ENC[AES256_GCM,data:1eoIDR5tUiZs,iv:tDSVMec1qgynwaukbberycixlbyoVn5WD0yvaGGgrIY=,tag:FTKg9H9V8d2zQ4bafYUUCw==,type:str]
        QIYU_MINIO_ENABLED: ENC[AES256_GCM,data:2Hz9t3Y=,iv:V4Q7sPBlQ6MtG9Wzr8GirULIaKI+3CrVf02OtALFfQY=,tag:vjF2fvV37Njc8f4uRD65oA==,type:str]
        QIYU_MINIO_ENDPOINT: ""
        QIYU_MINIO_ACCESS_KEY: ""
        QIYU_MINIO_SECRET_KEY: ""
        QIYU_MINIO_BUCKET: ""
        QIYU_MINIO_PUBLIC_BASE_URL: ""
        QIYU_MINIO_PUBLIC_READ: ENC[AES256_GCM,data:YapInnE=,iv:T1yoyHLUKvEJaymwS/D/aEOvGCYnI1AN8jfA+PLKIu8=,tag:kLIGIdJqbgjDtyl1s4l2Kw==,type:str]
        QIYU_MINIO_SEED_ENABLED: ENC[AES256_GCM,data:V7ggtSc=,iv:Y4YFSos4i9mdVVTAsfUAyIpe2v9qtfox28KaHQEA400=,tag:zxdMc/uvyRB26qap3sFKxA==,type:str]
admin_console:
    application_url: ENC[AES256_GCM,data:RaP0mRyYHUM4,iv:6aRptc6RtLZpMKBLIBtjrOTYQF7X3SoCwbrqqDT6B5k=,tag:snbrR+/uX7dLrV3ivPa4sw==,type:str]
    api_base_url: ENC[AES256_GCM,data:bGO9aUbXDYzm,iv:q2GIa+Bc0NTN+3sM92Gbx8XALlWGodGnximd0IjzB1I=,tag:Zvv48On+h2w9rXGQ+nL6AQ==,type:str]
wechat_miniprogram:
    api_base_url: ENC[AES256_GCM,data:DkKJu1/TdPh3,iv:1SOyRz9JLkpBbVh2Dlzy6COCI+/e8ae3MXDas4fi5O4=,tag:Pbgu3N45E1QOovj9+D1JJw==,type:str]
    upload_private_key: ENC[AES256_GCM,data:oh6lwsKhlKVw,iv:+qYEMTjZ6DxeeNj8aGZPDzlbkbowU7IFn3/+AAiYVvM=,tag:Mua/Stn1kWv/xtbHCRLENg==,type:str]
    robot: ENC[AES256_GCM,data:qA==,iv:NYOYCZVP3//np6T75g6+Uqc3zCTevDg6JGfNqRxBjMM=,tag:Sl86galjtl52ofzocj6UkQ==,type:int]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWUpaSERYMlZQOHg2L2Ir
            SHZrcnZNVVo1K3pELzErV3p5Q3ViM2FrUG53CjdlVGtKNmxITEpBUFI1cjhpTVVP
            NTNSa1J0ZGd2c3Y0VzlBRjRPU1JuUWMKLS0tIFAxNjcyQk9MNE1Fck42a1pmTVlq
            N1BmcktyUkY1NmVMYlVSOXNvN1ZNazgKgX2zBMMN+UdiTVjDtz+LenbfBn2r9ypu
            dJIlDLlx/XdAlxw2DmJQxNP2OZCT+zi5DtENq86VCk8aI3ec15JBOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ehph5e6803mx8wh9yu4guae0g298pmcpxw0ewgy6skg2jz2p4aps59cnzv
    lastmodified: "2026-09-15T17:23:22Z"
    mac: ENC[AES256_GCM,data:ylW0SyRvRvK3Pq8AIuEl7v08OpOdxhw/cqv9UjUDPea1WRkdSNcroi96Al2JcF9eXK+KSM2l3aYj0DvU4K2r5eWT49s7GU1DlR9ZPSkXM/c9OZDkBgsCWTNhqKzasX5n72w1o9DWJOQgQI8g8b2U4Ey3AXFee5sGMjV5GC0YrM4=,iv:FGRaQ+vFa383AxUmNgI6gKW/vQi0RDFJcHp3VT2yDrg=,tag:ZV1kCwGXKewQMk49GjfYhQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
