server:
  port: 8080

spring:
  application:
    name: qiyu-server
  profiles:
    default: local

springdoc:
  swagger-ui:
    path: /doc.html

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 7200
  is-concurrent: false
  is-share: false
  is-log: false
