// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","layout":false,"id":"1"},"2":{"path":"/","id":"2"},"3":{"path":"/","redirect":"/dashboard","parentId":"2","id":"3"},"4":{"path":"/dashboard","parentId":"2","id":"4"},"5":{"path":"/stores","parentId":"2","id":"5"},"6":{"path":"/appointments","parentId":"2","id":"6"},"7":{"path":"/checkin","parentId":"2","id":"7"},"8":{"path":"/service-orders","parentId":"2","id":"8"},"9":{"path":"/schedule","parentId":"2","id":"9"},"10":{"path":"/therapists","parentId":"2","id":"10"},"11":{"path":"/services","parentId":"2","id":"11"},"12":{"path":"/rooms","parentId":"2","id":"12"},"13":{"path":"/customers","parentId":"2","id":"13"},"14":{"path":"/members","parentId":"2","id":"14"},"15":{"path":"/coupons","parentId":"2","id":"15"},"16":{"path":"/reports","parentId":"2","id":"16"},"17":{"path":"/system/organizations","parentId":"2","id":"17"},"18":{"path":"/system/users","parentId":"2","id":"18"},"19":{"path":"/system/roles","parentId":"2","id":"19"},"20":{"path":"/system/menus","parentId":"2","id":"20"},"21":{"path":"/system/dictionaries","parentId":"2","id":"21"},"22":{"path":"/system/audit-logs","parentId":"2","id":"22"},"23":{"path":"/resources","redirect":"/schedule","parentId":"2","id":"23"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "layouts__AdminLayout" */'@/layouts/AdminLayout.tsx')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Dashboard__index" */'@/pages/Dashboard/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Stores__index" */'@/pages/Stores/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Appointments__index" */'@/pages/Appointments/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Checkin__index" */'@/pages/Checkin/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__ServiceOrders__index" */'@/pages/ServiceOrders/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Schedule__index" */'@/pages/Schedule/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Therapists__index" */'@/pages/Therapists/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__Services__index" */'@/pages/Services/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__Rooms__index" */'@/pages/Rooms/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__Customers__index" */'@/pages/Customers/index.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__Members__index" */'@/pages/Members/index.tsx')),
'15': React.lazy(() => import(/* webpackChunkName: "p__Coupons__index" */'@/pages/Coupons/index.tsx')),
'16': React.lazy(() => import(/* webpackChunkName: "p__Reports__index" */'@/pages/Reports/index.tsx')),
'17': React.lazy(() => import(/* webpackChunkName: "p__System__Organizations__index" */'@/pages/System/Organizations/index.tsx')),
'18': React.lazy(() => import(/* webpackChunkName: "p__System__Users__index" */'@/pages/System/Users/index.tsx')),
'19': React.lazy(() => import(/* webpackChunkName: "p__System__Roles__index" */'@/pages/System/Roles/index.tsx')),
'20': React.lazy(() => import(/* webpackChunkName: "p__System__Menus__index" */'@/pages/System/Menus/index.tsx')),
'21': React.lazy(() => import(/* webpackChunkName: "p__System__Dictionaries__index" */'@/pages/System/Dictionaries/index.tsx')),
'22': React.lazy(() => import(/* webpackChunkName: "p__System__AuditLogs__index" */'@/pages/System/AuditLogs/index.tsx')),
'23': React.lazy(() => import('./EmptyRoute')),
},
  };
}
